import { useState } from 'react';
import { motion } from 'framer-motion';
import {
  CheckCircle2, Download, RefreshCw, Share2, Clock,
  Smartphone, Laptop, Monitor, Tablet, Printer, Tv, Wifi, HelpCircle, Star,
} from 'lucide-react';
import type { TroubleshootingSession, DeviceType } from '../types';
import { categoryLabel } from '../agent/utils';
import { containerVariants, fadeUpVariants } from '../lib/motion';

interface ResolutionPageProps {
  session: TroubleshootingSession;
  onStartAnother: () => void;
}

const deviceIcons: Record<DeviceType, React.ElementType> = {
  phone:     Smartphone,
  laptop:    Laptop,
  desktop:   Monitor,
  tablet:    Tablet,
  printer:   Printer,
  'smart-tv': Tv,
  router:    Wifi,
  other:     HelpCircle,
  unknown:   HelpCircle,
};

function formatDuration(start: Date, end?: Date): string {
  const ms = (end ?? new Date()).getTime() - start.getTime();
  const minutes = Math.floor(ms / 60000);
  const seconds = Math.floor((ms % 60000) / 1000);
  if (minutes === 0) return `${seconds}s`;
  return `${minutes}m ${seconds}s`;
}

function formatSummary(raw: string): React.ReactNode {
  return raw.split('\n').map((line, i) => {
    const parts = line.split(/(\*\*[^*]+\*\*)/g);
    return (
      <span key={i} className="block">
        {parts.map((p, j) =>
          p.startsWith('**') && p.endsWith('**')
            ? <strong key={j} className="text-slate-800">{p.slice(2, -2)}</strong>
            : p,
        )}
      </span>
    );
  });
}

export default function ResolutionPage({ session, onStartAnother }: ResolutionPageProps) {
  const [rating, setRating] = useState(0);
  const [hoverRating, setHoverRating] = useState(0);
  const [saved, setSaved] = useState(false);
  const [copied, setCopied] = useState(false);

  const DeviceIcon = deviceIcons[session.device] ?? HelpCircle;
  const duration = formatDuration(session.startedAt, session.resolvedAt);
  const summary = session.solutionSummary ?? `Problem: ${session.problem}`;
  const catLabel = categoryLabel(session.category);
  const userMsgCount = session.messages.filter((m) => m.role === 'user').length;

  function handleSave() {
    const content = [
      '=== TechBridge Solution ===', '',
      `Date: ${session.startedAt.toLocaleDateString()}`,
      `Category: ${catLabel}`,
      `Device: ${session.device}`,
      `Time to resolve: ${duration}`, '',
      '--- Solution ---', '',
      summary.replace(/\*\*/g, ''), '',
      '=== Generated by TechBridge ===',
    ].join('\n');

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `techbridge-solution-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    setSaved(true);
    setTimeout(() => setSaved(false), 3000);
  }

  async function handleShare() {
    const text = `I fixed my tech problem with TechBridge!\n\n${summary.replace(/\*\*/g, '')}`;
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch { /* silent */ }
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-emerald-50 via-white to-blue-50 flex flex-col">

      {/* ── Header ──────────────────────────────────────────────────────────── */}
      <header className="w-full px-6 py-4 flex items-center justify-between max-w-3xl mx-auto">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 rounded-xl bg-blue-600 flex items-center justify-center">
            <span className="text-white font-bold text-sm leading-none">T</span>
          </div>
          <span className="font-bold text-slate-800 tracking-tight">TechBridge</span>
        </div>
        <motion.button
          whileHover={{ scale: 1.04 }} whileTap={{ scale: 0.97 }}
          onClick={onStartAnother}
          className="flex items-center gap-2 px-4 py-2 text-sm font-semibold text-blue-600 bg-blue-50 rounded-xl hover:bg-blue-100 transition-colors cursor-pointer border border-blue-100"
        >
          <RefreshCw size={14} /> New problem
        </motion.button>
      </header>

      {/* ── Main ─────────────────────────────────────────────────────────────── */}
      <motion.main
        className="flex-1 flex flex-col items-center px-4 pb-16 pt-4"
        variants={containerVariants}
        initial="hidden"
        animate="visible"
      >
        {/* Success banner */}
        <motion.div variants={fadeUpVariants}
          className="w-full max-w-2xl bg-gradient-to-r from-emerald-500 to-teal-400 rounded-3xl p-8 text-white text-center shadow-lg shadow-emerald-100 mb-6"
        >
          <motion.div
            initial={{ scale: 0 }}
            animate={{ scale: 1 }}
            transition={{ type: 'spring', stiffness: 260, damping: 18, delay: 0.15 }}
            className="w-20 h-20 rounded-full bg-white/20 flex items-center justify-center mx-auto mb-4"
          >
            <CheckCircle2 size={44} className="text-white" />
          </motion.div>
          <h1 className="text-3xl font-extrabold mb-2">Problem Solved! 🎉</h1>
          <p className="text-emerald-100 text-base leading-relaxed">
            You fixed your <strong className="text-white">{catLabel}</strong> issue on your{' '}
            <strong className="text-white">{session.device !== 'unknown' ? session.device : 'device'}</strong>.
            Great job!
          </p>

          <div className="flex justify-center gap-6 mt-5 pt-5 border-t border-white/20">
            <div className="text-center">
              <div className="text-2xl font-bold">{userMsgCount}</div>
              <div className="text-xs text-emerald-100">messages</div>
            </div>
            <div className="w-px bg-white/20" />
            <div className="text-center">
              <div className="text-2xl font-bold">{session.stepIndex + 1}</div>
              <div className="text-xs text-emerald-100">steps taken</div>
            </div>
            <div className="w-px bg-white/20" />
            <div className="flex flex-col items-center text-center">
              <div className="flex items-center gap-1 text-2xl font-bold">
                <Clock size={18} /> {duration}
              </div>
              <div className="text-xs text-emerald-100">time to resolve</div>
            </div>
          </div>
        </motion.div>

        {/* Solution summary */}
        <motion.div variants={fadeUpVariants}
          className="w-full max-w-2xl bg-white rounded-2xl border border-slate-100 shadow-sm p-6 mb-4"
        >
          <div className="flex items-center gap-3 mb-4">
            <div className="w-10 h-10 rounded-xl bg-blue-50 flex items-center justify-center">
              <DeviceIcon size={20} className="text-blue-600" />
            </div>
            <div>
              <h2 className="font-semibold text-slate-800 text-sm">Solution Summary</h2>
              <p className="text-xs text-slate-400">{catLabel} · {session.startedAt.toLocaleDateString()}</p>
            </div>
          </div>
          <div className="text-sm text-slate-600 leading-relaxed space-y-1 bg-slate-50 rounded-xl p-4 border border-slate-100">
            {formatSummary(summary)}
          </div>
        </motion.div>

        {/* Actions */}
        <motion.div variants={fadeUpVariants} className="w-full max-w-2xl grid grid-cols-2 sm:grid-cols-3 gap-3 mb-4">
          <motion.button whileHover={{ scale: 1.03 }} whileTap={{ scale: 0.97 }}
            onClick={handleSave}
            className="flex flex-col items-center gap-2 p-4 bg-white border border-slate-100 rounded-2xl shadow-sm hover:border-blue-100 hover:bg-blue-50 transition-all cursor-pointer group"
          >
            <Download size={20} className="text-slate-400 group-hover:text-blue-500 transition-colors" />
            <span className="text-xs font-semibold text-slate-600 group-hover:text-blue-600 transition-colors">
              {saved ? '✓ Saved!' : 'Save solution'}
            </span>
          </motion.button>

          <motion.button whileHover={{ scale: 1.03 }} whileTap={{ scale: 0.97 }}
            onClick={handleShare}
            className="flex flex-col items-center gap-2 p-4 bg-white border border-slate-100 rounded-2xl shadow-sm hover:border-blue-100 hover:bg-blue-50 transition-all cursor-pointer group"
          >
            <Share2 size={20} className="text-slate-400 group-hover:text-blue-500 transition-colors" />
            <span className="text-xs font-semibold text-slate-600 group-hover:text-blue-600 transition-colors">
              {copied ? '✓ Copied!' : 'Copy solution'}
            </span>
          </motion.button>

          <motion.button whileHover={{ scale: 1.03 }} whileTap={{ scale: 0.97 }}
            onClick={onStartAnother}
            className="col-span-2 sm:col-span-1 flex flex-col items-center gap-2 p-4 bg-blue-600 border border-blue-600 rounded-2xl shadow-sm hover:bg-blue-700 transition-all cursor-pointer"
          >
            <RefreshCw size={20} className="text-white" />
            <span className="text-xs font-semibold text-white">Start another</span>
          </motion.button>
        </motion.div>

        {/* Rating */}
        <motion.div variants={fadeUpVariants}
          className="w-full max-w-2xl bg-white rounded-2xl border border-slate-100 shadow-sm p-6 mb-4 text-center"
        >
          <h3 className="font-semibold text-slate-800 mb-1">How was your experience?</h3>
          <p className="text-sm text-slate-400 mb-4">Your feedback helps us improve TechBridge for everyone.</p>
          <div className="flex justify-center gap-2" role="group" aria-label="Rate your experience">
            {[1, 2, 3, 4, 5].map((star) => (
              <motion.button
                key={star}
                whileHover={{ scale: 1.2 }} whileTap={{ scale: 0.9 }}
                onClick={() => setRating(star)}
                onMouseEnter={() => setHoverRating(star)}
                onMouseLeave={() => setHoverRating(0)}
                aria-label={`Rate ${star} star${star > 1 ? 's' : ''}`}
                aria-pressed={rating === star}
                className="cursor-pointer"
              >
                <Star size={32} className={`transition-colors ${
                  star <= (hoverRating || rating) ? 'text-amber-400 fill-amber-400' : 'text-slate-200'
                }`} />
              </motion.button>
            ))}
          </div>
          {rating > 0 && (
            <motion.p initial={{ opacity: 0, y: 4 }} animate={{ opacity: 1, y: 0 }} className="mt-3 text-sm text-slate-500">
              {rating === 5 ? 'Wonderful! Thank you so much 🙏' : rating >= 3 ? 'Thanks for the feedback!' : "Sorry it wasn't perfect — we'll keep improving."}
            </motion.p>
          )}
        </motion.div>

        {/* Tips */}
        <motion.div variants={fadeUpVariants} className="w-full max-w-2xl bg-amber-50 border border-amber-100 rounded-2xl p-5 mb-4">
          <h3 className="font-semibold text-amber-800 mb-2 text-sm">💡 Keep your device healthy</h3>
          <ul className="text-sm text-amber-700 space-y-1.5">
            <li>• Restart your device once a week to keep it running smoothly.</li>
            <li>• Keep your apps and system up to date — updates fix bugs and improve security.</li>
            <li>• Back up your important photos and files regularly.</li>
            <li>• Never share your passwords or one-time codes with anyone.</li>
          </ul>
        </motion.div>

        {/* Bottom CTA */}
        <motion.div variants={fadeUpVariants} className="text-center mt-2">
          <p className="text-sm text-slate-400 mb-3">Have another tech problem?</p>
          <motion.button
            whileHover={{ scale: 1.04 }} whileTap={{ scale: 0.97 }}
            onClick={onStartAnother}
            className="inline-flex items-center gap-2 px-7 py-3 bg-blue-600 text-white rounded-2xl font-semibold text-sm shadow-md shadow-blue-100 hover:bg-blue-700 transition-colors cursor-pointer"
          >
            <RefreshCw size={16} /> Start a new session
          </motion.button>
        </motion.div>
      </motion.main>

      <footer className="text-center py-5 text-xs text-slate-400">
        TechBridge — Technology help for everyone · Built with ❤️
      </footer>
    </div>
  );
}
